name: Deploy Foodrecipe Fullstack App on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allow manual run from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Debug - list repo files
      - name: List repo files
        run: ls -R

      # Step 3: Test SSH connection (fail early if unreachable)
      - name: Test SSH connection
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          echo ">>> Testing SSH connection to ${{ secrets.EC2_HOST }} ..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} "echo ✅ SSH connection successful"

      # Step 4: Copy repo to EC2
      - name: Copy repo to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."                     # copy everything
          target: /home/ubuntu/foodrecipe # folder on EC2
          overwrite: true
          debug: true

      # Step 5: SSH into EC2 and deploy with Docker Compose
      - name: Deploy on EC2 with Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          debug: true
          script: |
            set -e
            echo ">>> Switching to project directory..."
            mkdir -p ~/foodrecipe
            cd ~/foodrecipe

            echo ">>> Installing prerequisites if missing..."
            # Git
            if ! command -v git &> /dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y git
            fi

            # Docker
            if ! command -v docker &> /dev/null; then
              echo ">>> Installing Docker..."
              sudo apt-get update -y
              sudo apt-get install -y ca-certificates curl gnupg lsb-release
              sudo mkdir -p /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update -y
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ubuntu
            fi

            echo ">>> Deploying with Docker Compose..."
            sudo docker compose down || true
            sudo docker compose up -d --build

            echo ">>> Running containers:"
            sudo docker ps -a
