name: Deploy Foodrecipe App on EC2 (No Docker)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: /home/ubuntu/foodrecipe

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            cd ~/foodrecipe

            echo ">>> Installing dependencies..."
            sudo apt-get update -y
            sudo apt-get install -y openjdk-17-jdk maven mysql-client nodejs npm nginx

            echo ">>> Building backend..."
            cd backend
            mvn clean package -DskipTests

            echo ">>> Restarting backend..."
            nohup java -jar target/*-SNAPSHOT.jar > backend.log 2>&1 &

            echo ">>> Building frontend..."
            cd ../frontend
            npm install
            npm run build

            echo ">>> Deploying frontend to Nginx..."
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx

            echo "✅ Deployment finished!"
