name: Deploy RecipeHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            set -e

            echo ">>> Ensuring deployment directory exists..."
            mkdir -p ~/foodrecipe
            cd ~/foodrecipe

            echo ">>> Installing required packages..."
            sudo apt-get update -y
            sudo apt-get install -y git openjdk-17-jdk maven mysql-client nodejs npm nginx

            # --- Backend ---
            if [ ! -d "backend" ]; then
              echo ">>> Cloning backend repo..."
              git clone https://github.com/Keerthipriya910/recipehub-aws-backend.git backend
            else
              echo ">>> Pulling latest backend changes..."
              cd backend
              git pull
              cd ..
            fi

            echo ">>> Building backend..."
            cd backend
            mvn clean package -DskipTests

            echo ">>> Restarting backend..."
            pkill -f 'java -jar' || true
            nohup java -jar target/*-SNAPSHOT.jar > backend.log 2>&1 &

            # --- Frontend ---
            if [ ! -d "../frontend" ]; then
              echo ">>> Cloning frontend repo..."
              git clone https://github.com/Keerthipriya910/recipehub-aws-frontend.git frontend
            else
              echo ">>> Pulling latest frontend changes..."
              cd ../frontend
              git pull
              cd ../backend  # Go back to deployment root
            fi

            echo ">>> Building frontend..."
            cd ../frontend
            npm install
            npm run build

            echo ">>> Deploying frontend to Nginx..."
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx

            echo "✅ Deployment finished!"
